config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cards#index'
  resources :cards do
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

      

app/models/card.rb
class Card < ApplicationRecord
  validates :title, :author, :price, :publisher, presence: true
  belongs_to :user

  def self.search(search)
    if search
      Card.where(' user_id LIKE(?) OR title LIKE(?) OR author LIKE(?) ', "%#{search}%", "%#{search}%", "%#{search}%") #複数カラムの検索
    else
      Card.all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         validates :nickname, :email, presence: { message: 'は、必須項目です'}, uniqueness: true     #バリデーション
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.includes(:user).order(created_at: :desc).page(params[:page]).per(10)  #-- 時系列順に並べる,ページネーション 
  end

  def new
    @card = Card.new
  end

  def create
    Card.create(card_params)
    redirect_to controller: :users, action: :show, id: current_user.id
  end

  def show
    @card = Card.find(params[:id])
  end

  def search
    @cards = Card.search(params[:keyword]).order(created_at: :desc).page(params[:page]).per(10)
    respond_to do |format|
      format.html #フォーマットを指定
      format.json
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    card = Card.find(params[:id])
    card.update(card_params)
    redirect_to controller: :users, action: :show, id: current_user.id
  end

  def destroy
    card = Card.find(params[:id])
    card.destroy
    redirect_to controller: :users, action: :show, id: current_user.id
  end

  private
  def card_params
    params.require(:card).permit(:title, :author, :price, :publisher, :comment).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @cards = @user.cards.order(created_at: :desc).page(params[:page]).per(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_menu.html.erb
<div class="hamberger_menu">
  <% if user_signed_in? %>
    <% if request.path.include?("users") && current_user.id == @user.id %>
      <%# 三本線 %>
      <div class="hamberger_line" >
        <span></span>
        <span></span>
        <span></span>
      </div>
        <%# クリックしたときのメニュ- %>
      <nav class="hamberger_list">
        <ul>
          <li><%= link_to "登録情報変更", "#"  %></li>
        </ul>
        <div class="log">
          <div class="log-day">
            最終更新日
          </div>
          <%= @cards.first.updated_at.strftime('%Y/%m/%d %H:%M:%S') %>
        </div>
      </nav>
      <div class="overlay"></div>
    <% end %>
  <% end %>
</div>

app/views/cards/edit.html.erb
<div class="contents">
  <div class="content__title">
    『<%= @card.title %>』の内容を編集
  </div>

  <%= form_with model: @card, class: :form, local: true do |f| %>
    <%= f.text_field :title, placeholder: :タイトル, class: :form__title %>
    <%= f.text_field :author, placeholder: :著者, class: :form__title %>
    <%= f.text_field :price, placeholder: :価格, class: :form__title %>
    <%= f.text_field :publisher, placeholder: :出版社, class: :form__title %>
    <%= f.text_area :comment, placeholder: :コメント, class: :form__text %>
    <%= f.submit '更新する', class: :form__btn %>
  <% end %>
</div>

app/views/cards/index.html.erb
<div class="contents">
  <%= form_with(url: search_cards_path, skip_enforcing_utf8: true, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-form__btn", name: nil%>
  <% end %>
  <div class="heading">
    <div class="heading__table">
      <div class= "heading__table__ids">
        ID
      </div>
    </div>
    <div class="heading__text">
      <div class= "heading__text__titols">
        <div class= "heading__text__titols__taitoru">
          タイトル
        </div>
      </div>
      <div class="heading__text__write">
        <div class="heading__text__write__tyosya">
          著者
        </div>
      </div>
      <div class="heading__names">
        読んだ人
      </div>
    </div>
  </div>
  <div class="wrapper">
    <% @cards.each do |card| %>
      <div class="content">
        <div class="content__left">
          <div class="content__left--id">
            <%= card.user_id %>
          </div>
        </div>
        <div class="content__right">
          <div class= "content__right__box">
            <div class="content__right__box__top">
              <%= link_to card.title, card_path(card.id), id: "content__right__top__titles" %>
            </div>
            <div class="content__right__box__bottom">
              <%= card.author %>
            </div>
          </div>
          <div class= "content__right__nicknames">
            <%= link_to card.user.nickname, user_path(card.user_id), class: "content__right__nicknames__links"%>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate(@cards) %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="contents">
  <div class="content__title">
    新規読書本
  </div>

  <%= form_with model: @card, class: :form, local: true do |f| %>
    <%= f.text_field :title, placeholder: :タイトル, class: :form__title %>
    <%= f.text_field :author, placeholder: :著者, class: :form__title %>
    <%= f.text_field :price, placeholder: :価格, class: :form__title %>
    <%= f.text_field :publisher, placeholder: :出版社, class: :form__title %>
    <%= f.text_area :comment, placeholder: :コメント, class: :form__text %>
    <%= f.submit '投稿する', class: :form__btn %>
  <% end %>
</div>

app/views/cards/search.html.erb
<div class="contents">
  <%= form_with(url: search_cards_path, skip_enforcing_utf8: true, local: true, method: :get, class: "search-form") do |form| %>
    <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
    <%= form.submit "検索", class: "search-form__btn", name: nil%>
  <% end %>
  <div class="heading">
    <div class="heading__table">
      <div class= "heading__table__ids">
        ID
      </div>
    </div>
    <div class="heading__text">
      <div class= "heading__text__titols">
        <div class= "heading__text__titols__taitoru">
          タイトル
        </div>
      </div>
      <div class="heading__text__write">
        <div class="heading__text__write__tyosya">
          著者
        </div>
      </div>
      <div class="heading__names">
        読んだ人
      </div>
    </div>
  </div>

  <div class="wrapper">
    <% @cards.each do |card| %>
      <div class="content">
        <div class="content__left">
          <div class="content__left--id">
            <%= card.user_id %>
          </div>
        </div>
        <div class="content__right">
          <div class= "content__right__box">
            <div class="content__right__box__top">
              <%= link_to card.title, card_path(card.id), id: "content__right__top__titles" %>
            </div>
            <div class="content__right__box__bottom">
              <%= card.author %>
            </div>
          </div>
          <div class= "content__right__nicknames">
            <%= link_to card.user.nickname, user_path(card.user_id), class: "content__right__nicknames__links"%>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate(@cards) %>
  </div>
</div>

app/views/cards/show.html.erb
<div class="contents">
  <div class="New">
    <div class="NewCardTitle">
      『<%= @card.title %>』の詳細
    </div>
    <div class="NewCardBox">
      <div class="NewCardAuthorName">
        タイトル
      </div>
      <div class="NewCardAuthor">
        <%= @card.title %>
      </div>
    </div>
    <div class="NewCardBox">
      <div class="NewCardAuthorName">
        著者
      </div>
      <div class="NewCardAuthor">
        <%= @card.author %>
      </div>
    </div>
    <div class="NewCardBox">
      <div class="NewCardAuthorName">
        価格
      </div>
      <div class="NewCardAuthor">
        <%= @card.price %>円
      </div>
    </div>
    <div class="NewCardBox">
      <div class="NewCardAuthorName">
        出版社
      </div>
      <div class="NewCardAuthor">
        <%= @card.publisher %>
      </div>
    </div>
    <div class="NewCardBox">
      <div class="NewCardAuthorName">
        コメント
      </div>
      <div class="NewCardAuthor">
        <%= @card.comment %>
      </div>
    </div>
    
    <div class="Btn">
          <%= link_to "戻る", :back, id: "Form__btn" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header__title">
        <%= link_to "book-card", root_path , class: "header__title--text" %>
      </div>
      <div class="header__right" >
        <% if user_signed_in? %>
          <% if request.path.include?("users") %>
            <%= link_to "本を投稿", new_card_path, class: "header__right--btn" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
          <% else %>
            <%= link_to "マイページ", user_path(current_user), class: "header__right--btn" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__right--btn" %>
          <% end %>
        <% else %>
          <%= link_to "ログイン", new_user_session_path, class: "header__right--btn" %>
          <%= link_to "新規登録", new_user_registration_path, class: "header__right--btn" %>
        <% end %>
      </div>
    </header>
     <%= render "cards/menu" %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="contents">
  <div class="New">
    <% if user_signed_in? && current_user.id == @user.id%>
      <div class="NewCardTitle">
        あなたが読んだ本
      </div>
    <% else %>
      <div class="NewCardTitle">
        <%= @user.nickname %>さんが読んだ本
      </div>
    <% end %>
    <div class="heading">
      <div class="heading__table">
        <div class= "heading__table__ids">
          ID
        </div>
      </div>
      <div class="heading__text">
        <div class= "heading__text__titols">
          <div class= "heading__text__titols__taitoru">
            タイトル
          </div>
        </div>
        <div class="heading__text__write">
          <div class="heading__text__write__tyosya">
            著者
          </div>
        </div>
      </div>
    </div>

    <% @cards.each do |card| %>
      <div class="content">
        <div class="content__left">
          <div class="content__left--id">
            <%= card.id %>
          </div>
        </div>
        <div class="content__right">
          <div class= "content__right__box">
            <div class="content__right__box__top">
              <%= link_to card.title, card_path(card.id), id: "content__right__top__titles" %>
            </div>
            <div class="content__right__box__bottom">
              <div class="content__right__box__bottom--author">
                <%= card.author %>
              </div>
            </div>
          </div>
          <div class= "content__right__edit">
            <% if user_signed_in? && current_user.id == card.user_id %>
              <div class= "content__right__edit__new">
                <%= link_to "編集", edit_card_path(card.id), id: "edit-pass"%>
              </div>
              <div class= "content__right__edit__destroy">
                <%= link_to "削除", card_path(card.id), method: :delete, id: "destroy-pass" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate(@cards) %>
  </div>
</div>